spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.253.88:8848

dubbo:
  scan:
    base-packages: learn.lhb.myshop.plus.business.controller,learn.lhb.myshop.plus.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://172.16.253.88:8848
    port: 80

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

level:
  learn.lhb.myshop.plus.provider.service.mapper: debug

# 开启 Feign 的 OKHttp 模式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret